
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezlutcrtxhnpavnpbmno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6bHV0Y3J0eGhucGF2bnBibW5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1ODA3NjgsImV4cCI6MjA1ODE1Njc2OH0.xrmedsc88b9GQgozDDN-ww0HgYrKdBNYMzqkzvIiGPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'supabase.auth.token'
  }
});

// Helper function to fetch functions with their module information
export async function getFunctionsWithModules() {
  return supabase
    .from('functions')
    .select(`
      *,
      modules (
        id,
        name,
        description
      )
    `);
}

