// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oibedgilqxcpaxqpskih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pYmVkZ2lscXhjcGF4cXBza2loIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1NDQwNzAsImV4cCI6MjA1NzEyMDA3MH0.r-scYrcr-9k2ACVvuQy9hzt7EAdHzZQwptoslcGSpHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);